CREATE TABLE ge_municipios(
  numg_municipio BIGSERIAL NOT NULL,
  nome_municipio character varying(50) NOT NULL,
  sigl_uf character varying(2) NOT NULL,
  flag_capital boolean NOT NULL,
  CONSTRAINT pk_se_municipios PRIMARY KEY (numg_municipio)
)WITH (OIDS=FALSE);

CREATE TABLE ge_pessoas(
  numg_pessoa BIGSERIAL NOT NULL,
  numr_cpfcnpj character varying(20),
  desc_nomepessoa character varying(100) NOT NULL,
  desc_sobrenomepessoa character varying(150),
  desc_email character varying(50),
  data_nascimento timestamp without time zone,
  desc_sexo character(1),
  desc_endereco character varying(250),
  numr_endereco character varying(10),
  desc_bairro character varying(50),
  desc_complemento character varying(250),
  numr_cep character varying(10),
  sigl_pais character(2),
  numr_dddtelefone character(3),
  numr_telefone character varying(15),
  numr_dddfax character(3),
  numr_fax character varying(15),
  desc_observacao character varying(255),
  data_cadastro DATE NOT NULL,
  data_ultimaalteracao timestamp without time zone,
  desc_tipo character varying(2),
  numg_municipio integer,
  desc_nomepai character varying(150),
  desc_nomemae character varying(150),
  desc_nacionalidade character varying(150),
  desc_naturalidade character varying(50),
  desc_orgaoexpedidor character varying(30),
  desc_estadocivil character varying(20),
  numr_filhos integer,
  numr_dddcelular character(3),
  numr_celular character varying(15),
  numr_dddtelefonecontato character(3),
  numr_telefonecontato character varying(15),
  numr_carteiraidentidade character varying(30),
  numg_usuarioalteracao integer,
  numg_usuariocadastro integer,
  CONSTRAINT pk_ge_pessoa PRIMARY KEY (numg_pessoa),
  CONSTRAINT ge_pessoa_desc_email_key UNIQUE (desc_email),
  CONSTRAINT ge_pessoa_numr_cpfcnpj_key UNIQUE (numr_cpfcnpj)
)WITH (OIDS=FALSE);